Authentication functionality (stateless)
Alexbaboshyn/simple_stackoverflow_api pull request #3
Opened 2017-12-07 16:25 UTC by Alexbaboshyn

2017-12-11 08:00 UTC, donasktello commented on app/controllers/tokens_controller.rb
> +    if token.is_a?ActiveModel::Errors
слишком сложно.
получаешь юзера
проверяешь пароль ? выдаёшь токен : не выдаёшь токен

2017-12-11 08:03 UTC, donasktello commented on app/controllers/tokens_controller.rb
> +    params.require(:token).permit(:email, :password)
не логично пихать почту и пароль под token.
это либо "логин", либо "юзер_креденшиалс"

2017-12-11 08:05 UTC, donasktello commented on app/models/user.rb
> +  has_many :sessions
минус

2017-12-11 08:06 UTC, donasktello commented on app/services/authenticatable.rb
> +      render json: {error: "unauthorized"}, status: 401
найди чего не хватает твоей аутентификации
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2017-12-11 08:08 UTC, donasktello commented on app/services/authenticatable.rb
> +  def authenticate
логика модуля очень правильная, ничего лишнего.
но само исполнение просто пиздец.
попробуй переписать не глядя, чтобы не повторить эту реализацию.
тут методы не нужны.

2017-12-11 08:10 UTC, donasktello commented on app/services/authenticatable.rb
> +  rescue
rescue на всё - за такое бы по рукам бил))
нельзя, ты должен отлавливать ошибки сугубо данного контекста.

2017-12-11 08:11 UTC, donasktello commented on app/services/json_web_token.rb
> +      payload.reverse_merge!(meta)
не понятно, что за issue, не выдумывай своего.
есть декод, есть енкод - их и оставь.

2017-12-11 08:12 UTC, donasktello commented on app/services/json_web_token.rb
> +      JWT.decode(token,
а что будет, если токен expired или invalid?
может быть тут стоит отлавливать ошибочки ? =)

2017-12-11 08:12 UTC, donasktello commented on app/services/json_web_token.rb
> +      {
этот метод лишний.
и что это за токен на 1 минуту?
ты шо проект для банка наркобароновского пишешь?
день

2017-12-11 08:14 UTC, donasktello commented on app/services/token.rb
> +class Token
класс лишний.
структура токена - строка и всё, не надо ничего придумывать. тем более всякие валидации.

2017-12-11 08:14 UTC, donasktello commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 20171207162009) do
спрячь схему

2017-12-13 08:01 UTC, donasktello commented on spec/controllers/users_controller_spec.rb
> +require 'rails_helper'
https://relishapp.com/rspec/rspec-expectations/v/2-0/docs/matchers/type-check-matchers
в каждый из контроллеров, где есть аутентификация 
на Authenticable

2017-12-13 08:05 UTC, donasktello commented on spec/services/questions_creator_spec.rb
> +    context do
удаляй контекст

2017-12-13 08:07 UTC, donasktello commented on spec/services/simple_stackoverflaw_token_spec.rb
> +require 'rails_helper'
убирай все дубли.

2017-12-13 10:26 UTC, donasktello commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 20171212122709) do
спроси у Лёши, как удалить.

2017-12-13 10:27 UTC, donasktello commented on spec/acceptance_helper.rb
> +Dir[Rails.root.join('spec/support/**/*.rb')].each { |f| require f }
Пора уже начинать включать голову при копировании, а не лишь бы работало.
Ну ёбана, пол утра распинался

2017-12-13 10:29 UTC, donasktello commented on spec/controllers/application_controller_spec.rb
> +RSpec.describe ApplicationController, type: :controller do
я же говорил, удали тесты для апп_контроллера.

если ты хочешь протестить поведение authenticable, так и тести его.

2017-12-13 10:30 UTC, donasktello commented on spec/requests/authentication_spec.rb
> +    it { expect(response.body).to eq "HTTP Token: Access denied.\n" }
где тест на наличие хедера WWW-Authenticate с параметрами?

2017-12-13 10:31 UTC, donasktello commented on spec/services/simple_stackoverflow_token_spec.rb
> +require 'rails_helper'
я же сказал, полностью без дублей переписать.
никаких expect/allow.to receive

2017-12-13 16:38 UTC, donasktello commented on config/routes.rb
>    resources :answers
не прошёл

2017-12-13 16:53 UTC, donasktello commented on spec/serializers/user_serializer_spec.rb
> +  let(:serialization) { ActiveModelSerializers::Adapter.create(serializer) }
удаляй весь тест и перепиши таким образом, и все остальные тесты сериалайзеров

```
require 'rails_helper'

RSpec.describe UserSerializer do
  subject { UserSerializer.new create(:user) }

  let(:attributes) { subject.attributes.keys }

  it { expect(attributes).to eq %i[id login email] }
end
```

2017-12-14 08:11 UTC, donasktello commented on spec/controllers/tokens_controller_spec.rb
> +        before { allow(user).to receive(:authenticate).with(resource_params[:password]).and_return(true) }
перепиши ёлкой.
отдельные бефор хуки воспринимаются, как стабы для разных переменных, хотя в твоём случае у тебя всё для одной переменной.

P.S. проверь весь проект, чтобы таких мест не было.

2017-12-14 08:16 UTC, donasktello commented on spec/services/users_creator_spec.rb
> +    before { allow(User).to receive(:new).with(params).and_return(user) }
ёлка[2]

2017-12-18 10:00 UTC, donasktello commented on spec/controllers/answers_controller_spec.rb
>    end
в тесте на индекс
`it { expect(response.body).to eq :collection.to_json }`
`.and_return(:collection)`

проверка одной и той же логической переменной? вот и вынеси её в переменную

2017-12-18 10:01 UTC, donasktello commented on app/controllers/application_controller.rb
> +  include ActionController::HttpAuthentication::Token::ControllerMethods
это тоже часть аутентификации, значит ей место где?

2017-12-18 10:04 UTC, donasktello commented on spec/controllers/questions_controller_spec.rb
>    end
опять же :collection в одну переменную вынеси

2017-12-18 10:24 UTC, donasktello commented on spec/services/simple_stackoverflow_token_spec.rb
> +  let(:user) { FactoryBot.create( :user) }
используй вместо `create` `build_stubbed`
Он возвращает юзера с застабанным айдишником.
Тебе же тут не нужно взаимодействие с бд, просто, чтобы существовал айдишник, а по скорости профит будет.

2017-12-18 10:27 UTC, donasktello commented on spec/acceptance_helper.rb
> +  config.include Permitter
не забываем удалить и файл, и инклюд

2017-12-18 10:32 UTC, donasktello commented on app/services/authenticatable.rb
> +module Authenticatable
это не автономный сервис, сам по себе он ничего не может.
это часть поведения, которое может быть унаследовано какими-то сервисами или чем-либо, поэтому этот модуль и saveable(который имеет такую же суть) вынеси в папочку services/concerns

2017-12-20 12:47 UTC, donasktello commented on app/services/simple_stackoverflow_token.rb
> +    AUTH_SECRET = Rails.application.secrets.secret_key_base
вынеси константу на уровень объекта класса

2017-12-20 12:57 UTC, donasktello commented on lor
> +[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0
чё это за говно?)

2017-12-21 12:45 UTC, kohigh requested changes

2017-12-21 12:45 UTC, kohigh commented on spec/controllers/answers_controller_spec.rb
> +      before { allow(Answer).to receive(:find).with('1').and_return(answer) }
там, где у тебя идёт стаб на один бефор_хук тоже вынеси в один контекст
"for exact question" например.
вот ты на уровне контроллера повторяющиеся куски кода объединяешь в бефор хуки для экшена апдейт и дестрой - это тебе подсказка делать тоже самое и на уровне тестов.

2017-12-21 12:45 UTC, kohigh commented on spec/controllers/answers_controller_spec.rb
> +  it { is_expected.to be_kind_of(Authenticatable) }
это тебе проверять во-первых не надо, во-вторых не этично.
ты напрямую не наследуешь authenticatable.
ты наследуешь application_controller, каким образом он решает все эти проблемы ты не знаешь(по идее)
поэтому, раз ты проверяешь application_controller на наличие этого модуля, тогда во всех контроллерах тебе будет достаточно проверить наследование от application_controller.
если бы у тебя не было теста на аппл_контроллер - тогда другой разговор, всё было бы в рамках положенногО, а иначе сейчас наличие этого теста лишает смысла сам факт существования теста на апп_ контроллер.

2017-12-21 12:45 UTC, donasktello commented on spec/controllers/questions_controller_spec.rb
> +      before { allow(Question).to receive(:find).with('1').and_return(question) }
тоже самое, Объедини по контекстам установки вопроса.

2017-12-21 12:45 UTC, donasktello commented on app/services/answer_creator.rb
> +    @question = Question.find(params[:question_id])
вынеси это на уровень контроллера. чтобы твой сервис работал с уже полученной сущностью.
Потому что хендлишь ошибку RecordNotFound ты на уровне контроллера в рамках сервиса ты её протестить не сможешь =)
\+ все файндеры, чтобы были в одном месте.
заодно избавишься от DRY (в AnswerSearcher и тут )

2017-12-21 12:45 UTC, donasktello commented on spec/requests/authentication_spec.rb
> +  let(:user) { FactoryBot.create(:user, attrs) }
почитай про гем database_cleaner  и добавь его так, чтобы у тебя зачищалась бд.

2017-12-26 13:37 UTC, kohigh requested changes

2017-12-26 13:37 UTC, donasktello commented on app/controllers/answers_controller.rb
> +  def parent
для AnswersController(ты же внутри него находишься) parent - ApplicationController.
выбирай внимательно названия методов)
не вижу ничего плохого, чтобы назвать ясно и понятно question, тем более внутри сервисов ты присваиваешь его, как question, а не, как parent.

2017-12-26 13:37 UTC, donasktello commented on app/controllers/answers_controller.rb
> +    parent ||= Question.find(resource_params[:question_id])
эти 2 строчки можно сократить до 
`Question.find(params[:question_id] || resource_params[:question_id])`
проверка на экшн тут лишнее усложнение, у тебя добавится ещё 50 экшенов, ты на каждый будешь проверять?)
и кэширование поправь)

2017-12-26 13:37 UTC, donasktello commented on spec/support/database_cleaner.rb
> +RSpec.configure do |config|
так.

датабейс_клинер нам нужен, для того, чтобы между тестами мы удостоверялись, что база данных была чиста и результаты между промежуточными тестами нам не помешали.

ты засунул всю эту тему в тот раздел тестов, где мы глушим любое взаимодействие с БД(юнит тесты).
Вопрос - зачем, если у нас итак БД будет пустая на всех тестах?)
датабейс клинер нужен там, где ты допускаешь взаимодействие с БД, в твоём случае это интеграционные тесты(где ты для аутентификации создаёшь юзера).
сейчас у тебя получается ровно наоборот.
удаляй этот файл и засунь нужные конфиги просто в acceptance_helper

2017-12-29 11:56 UTC, OleksiyNosov requested changes

2017-12-29 11:56 UTC, OleksiyNosov commented on config/application.rb
> +    config.middleware.use 'CatchJsonParseErrors'
лучше сразу передавать класс чем строку,
для этого подключи его `require './app/middleware/catch_json_parse_errors'`

2017-12-29 11:56 UTC, OleksiyNosov commented on db/seeds.rb
>  puts "Create #{ 4 } questions"
думаю здесь интерполяция не нужна

2017-12-29 11:56 UTC, OleksiyNosov commented on spec/controllers/answers_controller_spec.rb
> +          before { process :update, method: :patch, params: {id: answer_id, " ": resource_params }, format: :json }
я бы не использовал пробел в качестве ключа к хешу,
здесь можно проще написать без передачи параметров
`before { process :update, method: :patch, params: { id: answer_id }, format: :json }`
или передай явно неправильный ключ
`before { process :update, method: :patch, params: { id: answer_id, invalid_key: resource_params }, format: :json }`

2017-12-29 11:56 UTC, OleksiyNosov commented on spec/controllers/questions_controller_spec.rb
> +
лишняя строка

2017-12-29 11:56 UTC, OleksiyNosov commented on spec/controllers/questions_controller_spec.rb
> +        before { expect(Question).to receive(:find).with("0").and_raise ActiveRecord::RecordNotFound }
лишняя интерполяция

2017-12-29 11:56 UTC, OleksiyNosov commented on spec/requests/authentication_spec.rb
> +  let(:user) { FactoryBot.create(:user, attrs) }
убери FactoryBot, иначе непонятно, зачем ты его инклюдил в рспек.

2017-12-29 11:56 UTC, OleksiyNosov commented on spec/requests/authentication_spec.rb
> +    it('returns header "WWW-Authenticate"') { expect(response.header['WWW-Authenticate']).to eq "Token realm=\"Application\"" }
думаю в одинарных скобках лучше будет выглядеть
`{ expect(response.header['WWW-Authenticate']).to eq 'Token realm="Application"' }`

2017-12-29 11:56 UTC, OleksiyNosov commented on spec/services/answer_creator_spec.rb
> +    context '#valid params were passed' do
лишняя решетка, это ж не метод

2017-12-29 11:56 UTC, OleksiyNosov commented on spec/services/answer_creator_spec.rb
> +    context '#invalid params were passed' do
лишняя решетка [2]

2017-12-29 11:56 UTC, OleksiyNosov commented on spec/services/answer_searcher_spec.rb
> +    context '#searching answers on the question by body' do
лишняя решетка [3]

2017-12-29 11:56 UTC, OleksiyNosov commented on spec/services/answer_searcher_spec.rb
> +    context '#show all answers on the question' do
лишняя решетка, найди все)

2017-12-29 11:56 UTC, OleksiyNosov commented on spec/services/question_destroyer_spec.rb
> +  subject { QuestionDestroyer.new params }
можно ж сразу передать `question` как параметры без обьявления лишней переменной `params`

2017-12-29 11:56 UTC, OleksiyNosov commented on spec/support/authentication.rb
> +    allow(controller).to receive(:authenticate)
это мок, следовательно `expect`

2017-12-29 12:08 UTC, Alexbaboshyn commented on spec/controllers/answers_controller_spec.rb
> +          before { process :update, method: :patch, params: {id: answer_id, " ": resource_params }, format: :json }
мне кажется что всеже нагляднее будет передача именно неправильного require(параметра), или пустого, или неправильно написаного

2017-12-29 13:08 UTC, OleksiyNosov requested changes

2017-12-29 13:08 UTC, OleksiyNosov commented on .gitignore
> +.DS_Store
удали все закешированые файлы `.DS_Store`

2017-12-29 13:08 UTC, OleksiyNosov commented on README.md
>  * Rails version 5.0.6
убери `secrets.yml` из репы
добавь примеры конфиг файлов `database.yml` и назови `secret.database.yml`

также было б неплохо добавить шорткаты в ридми
```sh
cp config/secret.database.yml config/database.yml
cp config/secret.secrets.yml config/secrets.yml
```

2017-12-29 13:08 UTC, OleksiyNosov commented on spec/controllers/answers_controller_spec.rb
> +  let(:answer_id) { "1" }
лишняя интерполяция

2017-12-29 13:08 UTC, OleksiyNosov commented on spec/controllers/answers_controller_spec.rb
> +        before { allow(Question).to receive(:find).with("0").and_raise ActiveRecord::RecordNotFound }
лишняя интерполяция

2017-12-29 13:08 UTC, OleksiyNosov commented on spec/controllers/answers_controller_spec.rb
> +      let(:params) { { question_id: "1", answer: resource_params } }
лишняя интерполяция

2017-12-29 13:08 UTC, OleksiyNosov commented on spec/controllers/questions_controller_spec.rb
> +  let(:question_id) { "1" }
лишняя интерполяция

2017-12-29 13:08 UTC, OleksiyNosov commented on spec/controllers/questions_controller_spec.rb
> +      before { expect(Question).to receive(:find).with("0").and_raise ActiveRecord::RecordNotFound }
лишняя интерполяция

2017-12-29 14:16 UTC, OleksiyNosov requested changes

2017-12-29 14:16 UTC, OleksiyNosov commented on app/controllers/tokens_controller.rb
> +      render json: { token: token }, status: 201
думаю здесь можно не создавать лишнюю переменную `token` и сразу писать:
`render json: { token: SimpleStackoverflowToken.encode(user_id: user.id) }, status: 201`
плюс без лишних скобок для хеша

2017-12-29 14:16 UTC, OleksiyNosov commented on app/services/concerns/authenticatable.rb
> +module Authenticatable
перенеси модуль в папку консернов для контроллеров

2017-12-29 14:16 UTC, OleksiyNosov commented on app/services/simple_stackoverflow_token.rb
> +class SimpleStackoverflowToken
я бы переименовал на SimpleStackOverflowToken, но это опционально

2017-12-29 14:16 UTC, OleksiyNosov commented on db/seeds.rb
> +answers = FactoryBot.create_list :answer, 4
зачем создавать переменные которые не используешь

2017-12-29 14:16 UTC, OleksiyNosov commented on spec/requests/authentication_spec.rb
> +    it('returns "HTTP Token: Access denied.') { expect(response.body).to eq "HTTP Token: Access denied.\n" }
в коментаре нехватает двойной скобки

2017-12-29 14:24 UTC, Alexbaboshyn commented on app/controllers/tokens_controller.rb
> +      render json: { token: token }, status: 201
я думаю что мой вариант проще для зрительного восприятия хотя, посмотрю еще что скажет Слава

2017-12-29 14:39 UTC, Alexbaboshyn commented on spec/requests/authentication_spec.rb
> +    it('returns header "WWW-Authenticate"') { expect(response.header['WWW-Authenticate']).to eq "Token realm=\"Application\"" }
мне кажется что разницы нет

2017-12-29 14:54 UTC, OleksiyNosov requested changes

2017-12-29 14:54 UTC, OleksiyNosov commented on spec/services/simple_stackoverflow_token_spec.rb
>    describe '#decode' do
для методов класса я бы ставил точку вместо решетки

2017-12-29 14:54 UTC, OleksiyNosov commented on app/controllers/answers_controller.rb
> +    @question = Question.find(params[:question_id] || resource_params[:question_id])
я бы сделал без бефор хуков потому что мне они выглядят как лишнее телодвижение,
но хз насколько это правильное решение, так что опционально

2017-12-29 14:58 UTC, Alexbaboshyn commented on app/services/simple_stackoverflow_token.rb
> +class SimpleStackoverflowToken
Оставлю как есть, так и название приложения написано)

2017-12-29 15:08 UTC, Alexbaboshyn commented on app/controllers/answers_controller.rb
> +    @question = Question.find(params[:question_id] || resource_params[:question_id])
бефор екшены для этого и созданы

2017-12-29 15:14 UTC, OleksiyNosov commented on app/controllers/answers_controller.rb
> +    @question = Question.find(params[:question_id] || resource_params[:question_id])
ну так в самих методах переменные можно кешировать

2017-12-29 15:28 UTC, donasktello commented on app/controllers/tokens_controller.rb
> +      render json: { token: token }, status: 201
± оба правы, но я за зрительное восприятие, потому что водрузить эту конструкцию в итоговый хэш - реально нечитабельно выглядит.

оставляй пока так.

2017-12-29 16:37 UTC, kohigh submitted a review, later dismissed
мерджь, ничего преступного не вижу =)

2017-12-29 17:06 UTC, kohigh approved these changes

2017-12-29 18:15 UTC, merged