Authorization functionality
Alexbaboshyn/simple_stackoverflow_api pull request #4
Opened 2018-01-10 10:21 UTC by Alexbaboshyn

2018-01-10 13:45 UTC, OleksiyNosov commented on app/controllers/tokens_controller.rb
> +    @user ||= User.where('email ILIKE?', resource_params[:email]).first
я би не писал через `ILIKE`, потому что можно зарегестрироваться как `test@example.com` и получить токен под `test%`
`ILIKE` поддерживает Pattern Matching

2018-01-10 13:45 UTC, OleksiyNosov commented on app/controllers/users_controller.rb
> +      .on(:succeeded) { |resource| ConfirmationHandler.publish_confirmation(resource) }
думаю что логика отправки `ConfirmationHandler` должна вызываться в `UserCreator`б, а в контроллере просто должны быть разные варианты

2018-01-10 13:45 UTC, OleksiyNosov commented on app/controllers/users_controller.rb
> +    @user.update(state: 1)
я бы всё же писал символом или строкой, так статус который ты присваеваеш более понятен

2018-01-10 13:45 UTC, OleksiyNosov commented on app/controllers/users_controller.rb
> +    ConfirmationParser.parse(params[:id])
думаю лучше и логичней было бы назвать `token` вместо `id`
как-то непонятно зачем парсить токен

2018-01-10 13:45 UTC, OleksiyNosov commented on app/models/user.rb
> +    SimpleStackoverflowToken.encode({ user_id: self.id })
не вижу смысла делать метод который будет использоваться только один раз
я б переписал без него

2018-01-10 13:45 UTC, OleksiyNosov commented on app/policies/application_policy.rb
> +  def index?
зачем тебе весь этот код если ты его не используешь?
и особенно вот эти функции: `new?`, `edit?`

2018-01-10 13:45 UTC, OleksiyNosov commented on app/services/confirmation_handler.rb
> +      Redis.current.publish CHANNEL, { confirmation_token: user.confirmation_token,
я бы так не писал, думаю лучше было бы так:
```rb
Redis.current.publish CHANNEL, { 
  confirmation_token: user.confirmation_token,
  first_name: user.first_name,
  last_name: user.last_name,
  email: user.email,
  event_type: EVENT
}.to_json
```

2018-01-10 13:45 UTC, OleksiyNosov commented on config/routes.rb
> +      get 'confirm'
я б зделал символом

2018-01-10 13:45 UTC, OleksiyNosov commented on spec/controllers/answers_controller_spec.rb
> +              creator.send(:broadcast, :succeeded, answer)
здесь думаю лучше использовать хелпер `Dispatchable`, как Слава говорил

2018-01-10 13:45 UTC, OleksiyNosov commented on config/routes.rb
>    resources :answers, only: [:create, :update, :index, :destroy]
думаю лучше не нарушать духовные скрепы и писать в обычном порядке:
`[:index, :create, :update, :destroy]`

2018-01-10 13:45 UTC, OleksiyNosov commented on spec/controllers/tokens_controller_spec.rb
> +      context 'user didn\'t pass confirmation' do
здесь бы лучше использовать двойные скобки

2018-01-10 13:45 UTC, OleksiyNosov commented on spec/controllers/users_controller_spec.rb
> +  describe 'confirm' do
нужно добавить # чтобы показать что ты тестируешь инстанс метод

2018-01-10 13:45 UTC, OleksiyNosov commented on spec/models/user_spec.rb
> +    let(:subject) { FactoryBot.build_stubbed(:user) }
лишнее использование `FactoryBot`

2018-01-10 13:45 UTC, OleksiyNosov commented on spec/models/user_spec.rb
> +    it('creates user\'s confirmation_token') { expect(subject.send :confirmation_token).to eq token }
двойные скобки были бы лучше

2018-01-10 13:45 UTC, OleksiyNosov commented on spec/requests/authentication_spec.rb
> +  let(:attrs) { { first_name: 'Kaci', last_name: 'Ernser', email: 'test@test.com' } }
лишняя переменная, лучше удалить чтобы не засорять тэсты

2018-01-10 13:45 UTC, OleksiyNosov commented on spec/services/answer_updater_spec.rb
> +      before { allow(answer).to receive(:valid?).and_return(false) }
думаю лучше поменять последовательность вызова `errors` и `valid?` местами
так же как у тебя в `ServicesHandler`

2018-01-10 13:45 UTC, OleksiyNosov commented on spec/services/confirmation_handler_spec.rb
> +                                                        event_type: 'registration' }.to_json) }
красиво, но все же думаю так лучше не писать

2018-01-10 13:45 UTC, OleksiyNosov commented on spec/services/confirmation_parser_spec.rb
> +      before { allow(SimpleStackoverflowToken).to receive(:decode).with(confirmation_token).and_return(data) }
здесь можно спокойно протестировать без стабов и моков и проверять только ответ

2018-01-10 13:45 UTC, OleksiyNosov commented on spec/services/services_handler_spec.rb
> +    it('demonstrates that ServicesHandler can\'t have instances') do
двойные скобки

2018-01-10 13:45 UTC, OleksiyNosov commented on spec/controllers/questions_controller_spec.rb
> +            creator.send(:broadcast, :succeeded, question)
думаю лучше сохранять порядок тестирования:
`index show create update destroy`

2018-01-10 13:56 UTC, Alexbaboshyn commented on spec/requests/authentication_spec.rb
> +  let(:attrs) { { first_name: 'Kaci', last_name: 'Ernser', email: 'test@test.com' } }
не согласен что она лишняя

2018-01-10 14:03 UTC, Alexbaboshyn commented on app/models/user.rb
> +    SimpleStackoverflowToken.encode({ user_id: self.id })
в смысле только один раз, он будет использовать каждый раз при создании юзера, чем он плох?

2018-01-10 14:05 UTC, Alexbaboshyn commented on app/policies/application_policy.rb
> +  def index?
ну, на данном этапе у меня пандит только установлен но  не используется так как я считаю что для создания токена он не нужен. но нужен комментарий Славы

2018-01-10 14:07 UTC, OleksiyNosov commented on app/models/user.rb
> +    SimpleStackoverflowToken.encode({ user_id: self.id })
Один раз в смысле только в одном месте)))

2018-01-10 14:09 UTC, OleksiyNosov commented on spec/requests/authentication_spec.rb
> +  let(:attrs) { { first_name: 'Kaci', last_name: 'Ernser', email: 'test@test.com' } }
почему?

2018-01-10 14:26 UTC, Alexbaboshyn commented on app/controllers/tokens_controller.rb
> +    @user ||= User.where('email ILIKE?', resource_params[:email]).first
при создании юзера у нас не пройдет валидацию  test%@example.com, и то что при аутентификации для юзера будет принят как test%@example.com, так и test@example.com, ну я не знаю или это дыра в безопасности. но исправить можно без проблем)

2018-01-12 08:13 UTC, kohigh requested changes
Добавить user_id в question, answer; Авторизации

2018-01-12 08:13 UTC, kohigh commented on app/controllers/tokens_controller.rb
> +    if @user.confirmed?
авторизация

2018-01-12 08:13 UTC, kohigh commented on app/controllers/tokens_controller.rb
> +    @user ||= User.where('email ILIKE?', resource_params[:email]).first
\+ и find_by

2018-01-12 08:13 UTC, kohigh commented on app/controllers/users_controller.rb
> +      .on(:succeeded) { head 201 }
ресурс + 201

2018-01-12 08:13 UTC, kohigh commented on app/controllers/users_controller.rb
> +      .on(:succeeded) { |resource| ConfirmationHandler.publish_confirmation(resource) }
\+

2018-01-12 08:13 UTC, kohigh commented on app/controllers/users_controller.rb
> +    @user.update(state: 1)
переписать

2018-01-12 08:13 UTC, kohigh commented on app/controllers/users_controller.rb
> +    ConfirmationParser.parse(params[:id])
\+ переписать DRY

2018-01-12 08:13 UTC, kohigh commented on app/models/user.rb
> +    SimpleStackoverflowToken.encode({ user_id: self.id })
удаляй

2018-01-12 08:13 UTC, donasktello commented on app/policies/application_policy.rb
> +  def index?
\+
удали всё лишнее

2018-01-12 08:13 UTC, donasktello commented on app/services/confirmation_parser.rb
> +class ConfirmationParser
удаляем

2018-01-12 08:13 UTC, donasktello commented on config/routes.rb
> +      get 'confirm'
\+

2018-01-12 08:13 UTC, donasktello commented on config/routes.rb
>    resources :answers, only: [:create, :update, :index, :destroy]
\+

2018-01-18 14:29 UTC, OleksiyNosov commented on app/controllers/concerns/authenticatable.rb
> +  def user(token = params[:token])
лучше так не писать, в данном случае мы добавляем скрытую логику по тому что при вызове метода `user` никто не ожидает что метод пойдёт в параметры и возьмёт токен, думаю нужно как минимум переименовать

2018-01-18 14:29 UTC, OleksiyNosov commented on app/controllers/users_controller.rb
> +    head 200, message: 'user confirmed'
думаю здесь всё же лучше писать не `message`, а `body` потому что в ином случае нам нужно было бы отправлять `204 no content`, а `200 ok`

2018-01-18 14:29 UTC, OleksiyNosov commented on app/controllers/users_controller.rb
> +    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation).to_h
думаю можно было бы перейти на `rails 5.1.4` и избавить от этого костыля `.to_h`

2018-01-18 14:29 UTC, OleksiyNosov commented on app/models/user.rb
> +  scope :confirmed, -> { where('state > 0') }
метод нигде не используется

2018-01-18 14:29 UTC, OleksiyNosov commented on app/policies/answer_policy.rb
> +    return true if user.id == answer.user_id
зачем так сложно? можно ж так:
```rb
def update?
  user.id == answer.user_id
end
```

2018-01-18 14:29 UTC, OleksiyNosov commented on app/policies/answer_policy.rb
> +    def answer
думаю что это лишний метод, потому что по названию `AnswerPolicy` и методу `record` и так понятно чем мы оперируем

2018-01-18 14:29 UTC, OleksiyNosov commented on config/routes.rb
> +  resources :answers, only: [:create, :index, :update, :destroy]
думаю лучше придерживаться стандартно последовательности рельс:
`[:index, :show, :create, :update, :destroy]`

2018-01-18 14:29 UTC, OleksiyNosov commented on spec/rails_helper.rb
> +require "pundit/rspec"
думаю лучше использовать одинарные скобки

2018-01-18 14:29 UTC, OleksiyNosov commented on spec/publishers/pub_sub_spec.rb
> +RSpec.describe PubSub do
думаю можно было бы добавить еще интеграционный тест

2018-01-18 14:48 UTC, Alexbaboshyn commented on app/controllers/concerns/authenticatable.rb
> +  def user(token = params[:token])
ну, у меня метод user в аутентификации только и присутствует и он подразумевает что токен в него будет передан либо из params при confirmation либо из request head при аутентификации

2018-01-18 14:49 UTC, Alexbaboshyn commented on app/controllers/tokens_controller.rb
> +    @user ||= User.find_by!(email: resource_params[:email].downcase)
он никак не должен цеплять пандит, это pundit цепляет его

2018-01-18 14:49 UTC, Alexbaboshyn commented on app/models/user.rb
> +  scope :confirmed, -> { where('state > 0') }
это скоуп а не метод

2018-01-18 14:52 UTC, Alexbaboshyn commented on spec/controllers/users_controller_spec.rb
> +  describe 'GET #confirm' do
он тут не нужен

2018-01-18 15:16 UTC, Alexbaboshyn commented on config/routes.rb
> +  resources :answers, only: [:create, :index, :update, :destroy]
не знаю про стандартную последовательности CRUD

2018-01-19 14:17 UTC, kohigh requested changes

2018-01-19 14:17 UTC, donasktello commented on app/controllers/answers_controller.rb
> +    AnswerCreator.new(resource_params.merge(user: current_user), @question)
авторизация на валидность юзера

2018-01-19 14:17 UTC, donasktello commented on app/controllers/concerns/authenticatable.rb
> +  def user(token)
%_user_from_token

2018-01-19 14:17 UTC, donasktello commented on app/controllers/tokens_controller.rb
> +    if pundit_user.authenticate resource_params[:password]
@user

2018-01-19 14:17 UTC, donasktello commented on app/controllers/users_controller.rb
> +  def pundit_user
убрать

2018-01-19 14:17 UTC, donasktello commented on app/controllers/users_controller.rb
> +    authorize User
@current_user = user(params[:token])

2018-01-19 14:17 UTC, donasktello commented on app/models/user.rb
> +  scope :confirmed, -> { where('state > 0') }
\-

2018-01-19 14:17 UTC, donasktello commented on app/policies/answer_policy.rb
> +    def answer
\-

2018-01-19 14:17 UTC, donasktello commented on app/policies/application_policy.rb
> +  end
приватный метод на валидность юзера

2018-01-19 14:17 UTC, donasktello commented on app/policies/question_policy.rb
> +    def question
\-

2018-01-19 14:17 UTC, donasktello commented on app/publishers/pub_sub.rb
> +    def call
client

2018-01-23 13:21 UTC, OleksiyNosov commented on app/controllers/tokens_controller.rb
> +  before_action :pundit_user, only: :create
думаю здесь `before_action` не нужен так как данный метод используется только в одном экшене

2018-01-23 13:21 UTC, OleksiyNosov commented on app/controllers/users_controller.rb
> +    user = user_from_token(params[:token])
ты здесь создаёшь лишнюю переменную `user` потому что твой метод `user_from_token` и так делает запись в `@current_user`

2018-01-23 13:21 UTC, OleksiyNosov commented on .gitignore
> +.dump.rdb
напиши без точки `dump.rdb` и удали из хеша

2018-01-23 13:21 UTC, OleksiyNosov commented on app/controllers/answers_controller.rb
> +    AnswerCreator.new(resource_params.merge(user: current_user), @question)
думаю было бы правильней делать строчку отступа между авторизацией пользователя и основной логикой экшена, поскольку это два разных действия

2018-01-23 13:21 UTC, OleksiyNosov commented on app/models/user.rb
> +  has_many :questions
здесь можно было бы убрать разделяющую строчку, поскольку здесь похожие по смыслу действия

2018-01-23 13:21 UTC, OleksiyNosov commented on app/services/user_creator.rb
> +  def resource
не думаю что `resource` подходящее название поскольку содержит скрытую логику создания юзера, думаю лучше было бы назвать create_user, или закинуть код в метод `call` ведь во всех остальных методах `call` у  тебя логика обработки туда и зашита

2018-01-23 13:21 UTC, OleksiyNosov commented on spec/controllers/questions_controller_spec.rb
> +        context 'user is author of the question' do
здесь лучше писать юзер проходит авторизацию `with authorization` ведь у тебя может изменится логика авторизации и тебе прийдётся переписывать данный контекст. для проверки или юзер является автором у тебя есть `specs/policies/`

2018-01-23 13:21 UTC, OleksiyNosov commented on app/controllers/answers_controller.rb
> +    AnswerUpdater.new(@answer, resource_params)
мне кажется что не логично когда у юзера есть возможность поменять айдишник вопроса при апдейте

2018-01-23 13:21 UTC, OleksiyNosov commented on spec/policies/answer_policy_spec.rb
> +    it "refuses access if user is not confirmed" do
лишние двойные скобки во всех тестах на авторизацию

2018-01-23 13:21 UTC, OleksiyNosov commented on spec/policies/user_policy_spec.rb
> +  let(:nil_user) { nil }
зачем тебе для этого переменная? можно ж сразу нил передать

2018-01-23 13:21 UTC, OleksiyNosov commented on config/routes.rb
> +  resources :users, only: :create do
как-то не логично что нету роута `update` и юзер не может поменять `first_name` и `last_name`

2018-01-23 13:21 UTC, OleksiyNosov commented on spec/services/services_handler_spec.rb
> +    it("demonstrates that ServicesHandler can't have instances") do
думаю что здесь демонстрация того что `ServicesHandler` является абстрактным классом)))

2018-01-23 13:21 UTC, OleksiyNosov commented on spec/controllers/answers_controller_spec.rb
> +        before { allow(subject).to receive(:authorize).and_raise Pundit::NotAuthorizedError }
когда мокаешь рейз ошибки лучше писать `expect` вместо `allow`, и не аргументы не нужно передавать
перепиши везде где есть `ActiveRecord::RecordNotFound` или `Pundit::NotAuthorizedError`

2018-01-23 13:21 UTC, OleksiyNosov commented on app/controllers/application_controller.rb
> +  include Pundit
добавь тест на подключение модуля

2018-01-23 13:23 UTC, Alexbaboshyn commented on app/controllers/answers_controller.rb
> +    AnswerUpdater.new(@answer, resource_params)
почему? если сообразил что ответ ни к тому вопросу написал

2018-01-23 13:26 UTC, Alexbaboshyn commented on app/controllers/users_controller.rb
> +    user = user_from_token(params[:token])
сначала было так как ты говоришь, но я изменил. я думаю что так будет быстрее потому что сразу обращаюсь к переменной а не к методу. плюс так понятнее будет стороннему разработчику что здесь происходит.

2018-01-23 13:30 UTC, Alexbaboshyn commented on app/services/user_creator.rb
> +  def resource
я никак не пойму твоих замечаний по поводу скрытой логики, ты о чем? я специально не закидывал код в метод call для того чтобы метод не был громоздким. Когда метод состоит из дохера строк, по мне так это не гуд.

2018-01-23 13:33 UTC, Alexbaboshyn commented on app/controllers/tokens_controller.rb
> +  before_action :pundit_user, only: :create
какая разница в скольких екшнах я его использую?

2018-01-25 12:30 UTC, OleksiyNosov commented on app/controllers/tokens_controller.rb
> +    pundit_user
можно спокойно удалить вызов `pundit_user`, при авторизации он и так происходит

2018-01-25 12:30 UTC, OleksiyNosov commented on app/controllers/users_controller.rb
> +    render json: { message: 'user confirmed' }, satus: 200
лишнее указание статуса, по дефолту и так `200`

2018-01-25 12:30 UTC, OleksiyNosov commented on spec/controllers/answers_controller_spec.rb
> +        before { expect(Question).to receive(:find).with('0').and_raise ActiveRecord::RecordNotFound }
аргумент можно не передавать

2018-01-25 12:30 UTC, OleksiyNosov commented on app/controllers/questions_controller.rb
> +      .on(:succeeded) { |resource| render json: resource, status: 201 }
думаю лучше было бы писать `serialized_resource` вместо `resource`, так более понятней что сериализация происходит не здесь и вариант вставить `serializer: OtherUserSerializer` не пройдет

2018-01-25 14:10 UTC, kohigh requested changes

2018-01-25 14:10 UTC, kohigh commented on app/controllers/tokens_controller.rb
> +  before_action :pundit_user, only: :create
\+

2018-01-25 14:10 UTC, kohigh commented on app/controllers/users_controller.rb
> +    user = user_from_token(params[:token])
\+

2018-01-25 14:10 UTC, kohigh commented on app/policies/answer_policy.rb
> +    user_is_author?
валидации на валидность юзера

2018-01-25 14:10 UTC, kohigh commented on spec/controllers/answers_controller_spec.rb
> +        before { allow(subject).to receive(:authorize).and_raise Pundit::NotAuthorizedError }
\+

2018-01-25 14:10 UTC, kohigh commented on app/services/user_creator.rb
> +  def resource
\+

2018-01-25 14:10 UTC, kohigh commented on app/services/user_creator.rb
> +    attributes = ActiveModelSerializers::SerializableResource.new(@resource).as_json
инкапсулировать в ServicesHandler.

2018-01-25 14:10 UTC, donasktello commented on app/controllers/questions_controller.rb
> +      .on(:succeeded) { |resource| render json: resource, status: 201 }
\+

2018-01-25 14:10 UTC, donasktello commented on app/controllers/tokens_controller.rb
> +    pundit_user
перепиши на current_user

2018-01-25 14:10 UTC, donasktello commented on app/controllers/users_controller.rb
> +    render json: { message: 'user confirmed' }, satus: 200
реализовать обработку 401

2018-01-29 13:50 UTC, OleksiyNosov commented on app/controllers/users_controller.rb
> +      render json: { message: 'user confirmed' }, satus: 200
лишнее указание статуса, по умолчанию он и так `200`

2018-01-29 13:50 UTC, OleksiyNosov commented on app/services/answer_updater.rb
лишняя строка

2018-01-29 13:50 UTC, OleksiyNosov commented on app/models/question.rb
>    validates :title, :body,  presence: true
лишний пробел

2018-01-29 13:50 UTC, OleksiyNosov commented on spec/services/services_handler_spec.rb
> +    it("demonstrates that ServicesHandler is an abstract class") do
лишнее использование двойных скобок

2018-01-29 13:50 UTC, OleksiyNosov commented on spec/controllers/questions_controller_spec.rb
> +        context 'question was not updated' do
подними блок `question was not updated` на одну табуляцию выше 116-134

2018-01-29 13:50 UTC, OleksiyNosov commented on spec/controllers/users_controller_spec.rb
> +      it('returns header "WWW-Authenticate"') { expect(response.header['WWW-Authenticate']).to eq "Token realm=\"Application\"" }
лишнее использование эскейп последовательностей, можно и попроще:
`.to eq 'Token realm="Application"'`

2018-01-29 13:50 UTC, OleksiyNosov commented on Gemfile.lock
>      json (2.1.0)
в классе `CatchJsonParseErrors` [app/middleware/catch_json_parse_errors.rb](https://github.com/Alexbaboshyn/simple_stackoverflow_api/blob/authorization_functionality/app/middleware/catch_json_parse_errors.rb)

- лишнее использование блока `begin` [ruby-style-guide](https://github.com/bbatsov/ruby-style-guide#begin-implicit)
- лишняя строка перед `rescue`
- в регулярке лучше ипользовать `.match?(r{regex})` [ruby-style-guide](https://github.com/bbatsov/ruby-style-guide#percent-r)
- лишнее использование двойных скобок [ruby-style-guide](https://github.com/bbatsov/ruby-style-guide#consistent-string-literals)
- лишний пробел при создании пустого массива

2018-01-29 13:50 UTC, OleksiyNosov commented on spec/controllers/answers_controller_spec.rb
> +          context 'question was not updated' do
контекст `'question was not updated'` не подходит по смыслу потому-что не говорит что должно случится для того чтобы вернулся `422` статус и ошибки

2018-01-29 13:50 UTC, OleksiyNosov commented on spec/controllers/answers_controller_spec.rb
> +                updater.send(:broadcast, :succeeded, answer)
думаю здесь лучше использовать хелпер `Dispatchable`, как Слава говорил

2018-01-29 15:10 UTC, OleksiyNosov commented on spec/controllers/tokens_controller_spec.rb
>          it('returns created token') { expect(response.body).to eq ({ token: token }).to_json }
пробел межу вызовом метода `eq` и передачей параметров [ruby-style-guide](https://github.com/bbatsov/ruby-style-guide#parens-no-spaces)

2018-01-29 15:10 UTC, OleksiyNosov commented on spec/controllers/answers_controller_spec.rb
> +            before { process :update, method: :patch, params: {id: answer_id, ' ': resource_params }, format: :json }
не хватает пробела перед фигурными скобками

2018-01-29 15:10 UTC, OleksiyNosov commented on spec/controllers/tokens_controller_spec.rb
> +      before {sign_in user}
не хватает пробелов в скобках

2018-01-29 16:06 UTC, kohigh requested changes

2018-01-29 16:06 UTC, kohigh commented on Gemfile
> +gem 'homie'
допиши лаконичное описание гемов

2018-01-29 16:06 UTC, kohigh commented on app/controllers/answers_controller.rb
> +  def authorization
метод действие

2018-01-29 16:06 UTC, kohigh commented on app/controllers/questions_controller.rb
> +  def authorization
переименовать

2018-01-29 16:06 UTC, kohigh commented on app/controllers/users_controller.rb
> +      render json: { message: 'user confirmed' }, satus: 200
\+ и внимательнее к синтаксису

2018-01-29 16:06 UTC, donasktello commented on spec/controllers/answers_controller_spec.rb
> +                updater.send(:broadcast, :succeeded, answer)
\+

2018-01-29 16:06 UTC, donasktello commented on spec/controllers/answers_controller_spec.rb
> +          context 'question was not updated' do
\+

2018-01-29 16:06 UTC, donasktello commented on spec/controllers/questions_controller_spec.rb
> +        context 'question was not updated' do
\+

2018-01-29 16:06 UTC, donasktello commented on spec/controllers/users_controller_spec.rb
> +      it('returns header "WWW-Authenticate"') { expect(response.header['WWW-Authenticate']).to eq "Token realm=\"Application\"" }
\+

2018-01-29 16:06 UTC, donasktello commented on spec/services/answer_updater_spec.rb
> +      before { allow(answer).to receive(:valid?).and_return(false) }
\+

2018-01-29 16:06 UTC, donasktello commented on spec/services/services_handler_spec.rb
> +    it("demonstrates that ServicesHandler is an abstract class") do
\+

2018-01-30 12:50 UTC, OleksiyNosov commented on spec/controllers/users_controller_spec.rb
> +    context 'new user was not created' do
'new user was not created' - почему?
было бы неплохо написать причину неудачного результата

2018-01-30 12:50 UTC, OleksiyNosov commented on spec/policies/token_policy_spec.rb
> +      expect(subject).not_to permit(User.new, :Token)
было б неплохо с меленькой буквы писать символ `permit(User.new, :token)`

2018-01-30 12:50 UTC, OleksiyNosov commented on spec/requests/authentication_basic_spec.rb
> +  let(:user) { create(:user, state: 1) }
думаю лучше было бы через `state: :confirmed`, так более понятней какой статус присваеваешь

2018-01-30 12:50 UTC, OleksiyNosov commented on spec/requests/authentication_basic_spec.rb
> +  before { post '/tokens', headers: headers }
думаю стоило бы завернуть всю  эту движуху в дескрайб:
```
describe 'POST #tokens' do
  # your code here
end
```

2018-01-30 12:50 UTC, OleksiyNosov commented on spec/requests/authentication_basic_spec.rb
> +      it('returns header "WWW-Authenticate"') { expect(response.header['WWW-Authenticate']).to eq "Basic realm=\"Application\"" }
можно и без интерполяции написать

2018-01-30 12:50 UTC, OleksiyNosov commented on spec/services/answer_creator_spec.rb
>  RSpec.describe AnswerCreator do
сделай строчку отступа между `require` и `RSpec` во всех хелперах

2018-01-30 13:34 UTC, OleksiyNosov commented on spec/controllers/users_controller_spec.rb
> +      before { broadcast_succeeded creator, user}
не хватает пробела перед фигурной скобкой

2018-01-30 14:38 UTC, kohigh requested changes

2018-01-30 14:38 UTC, donasktello commented on spec/policies/question_policy_spec.rb
> +  let(:question) { Question.new(user_id: 1) }
добавить хелпер для инициализации моделей дублей

2018-01-30 14:38 UTC, donasktello commented on spec/policies/token_policy_spec.rb
> +      expect(subject).not_to permit(User.new, :Token)
\+

2018-01-30 14:38 UTC, donasktello commented on spec/services/answer_updater_spec.rb
> +      before do
инкапсулировать в общем хелпере для ServicesHandler

broadcast_succeeded
broadcast_failed
serialize

2018-09-27 06:26 UTC, merged